config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  get 'users/:id', to: 'users#show', as: 'user_show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :events do
    member do
      get :attend_event
    end
  end
  # Defines the root path route ("/")
  root 'events#index'

  resources :event_attendances
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  validates_presence_of :name, :description, :date, :time, :location
  validates :name, uniqueness: true

  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  has_many :event_attendances, dependent: :destroy
  has_many :attendees, through: :event_attendances, source: :user, dependent: :destroy

  scope :past, -> { where('date <= ?', Time.now) }
  scope :upcoming, -> { where('date >= ?', Time.now) }

  def past?
    date <= Time.now
  end

  def upcoming?
    date >= Time.now
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

# The EventsController handles CRUD operations for events.
# It inherits from ApplicationController, which is the base controller class.
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  # GET /events
  # Retrieves all events from the database and assigns them to @events instance variable.
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  # GET /events/new
  # Initializes a new Event object and assigns it to @event instance variable.
  def new
    @event = Event.new
  end

  # POST /events
  # Creates a new event with the provided parameters.
  # If the event is successfully saved, it sets a flash notice and redirects to the root path.
  # Otherwise, it renders the new template with the status :unprocessable_entity.
  def create
    @event = Event.new(event_params)
    @event.creator = current_user

    if @event.save
      flash[:notice] = 'Event created!'
      EventCreatorMailer.with(event: @event).event_created_email.deliver_now
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      flash[:notice] = 'Event Updated!'
      redirect_to @event
    else
      flash.now[:notice] = 'Something went wrong!'
      render 'edit'
    end
  end

  def attend_event
    @event = Event.find(params[:id])
    redirect_to new_event_attendance_path(event: @event)
  end

  def destroy
    @event = Event.find(params[:id])

    if @event.destroy
      flash[:notice] = 'Event deleted!'
      redirect_to root_path
    else
      flash.now[:notice] = 'Something went wrong!'
      render :show
    end
  end

  private

  # Strong parameters method for event attributes.
  # It permits the required attributes for an event: description, date, time, and location.
  def event_params
    params.require(:event).permit(:name, :description, :date, :time, :location)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<div class="container-fluid p-5 bg-light">
  <h2>Edit Event</h2>

  <%= form_for @event do |f| %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
    </div>

    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_area :description, autofocus: true, autocomplete: "description" %>
    </div>

    <div class="field">
      <%= f.label :location %><br />
      <%= f.text_field :location, autofocus: true, autocomplete: "location" %>
    </div>

    <div class="field">
      <%= f.label :date %><br />
      <%= f.date_field :date, autofocus: true, autocomplete: "date" %>
    </div>

    <div class="field">
      <%= f.label :time %><br />
      <%= f.time_field :time, autofocus: true, autocomplete: "time" %>
    </div><br>

    <div class="actions">
      <%= f.submit "Edit event" %>
    </div>
  <% end %>
</div>

app/views/events/index.html.erb
<h1>Event List:</h1><br>
<% if @events.empty? %>
  There are no events yet!
<% else %>
  <h5>Past events:</h5>
  <ol class="list-group list-group-numbered">
    <% @events.past.each do |event| %>
      <li class="list-group-item d-flex justify-content-between align-items-start">
        <div class="ms-2 me-auto">
          <div class="fw-bold"><%= link_to event.name.capitalize, event_path(event) %></div>
          <%= event.description.capitalize %>
        </div>
      </li>
    <% end %><br>
  </ol>
  <h5>Upcoming events:</h5>
  <ol class="list-group list-group-numbered">
    <% @events.upcoming.each do |event| %>
      <li class="list-group-item d-flex justify-content-between align-items-start">
        <div class="ms-2 me-auto">
          <div class="fw-bold"><%= link_to event.name.capitalize, event_path(event) %></div>
          <%= event.description.capitalize %>
        </div>
      </li>
    <% end %>
  </ol>
<% end %><br>
<% if user_signed_in? %>
  <%= button_to 'Create Event', new_event_path, method: :get %>
<% end %>

app/views/events/new.html.erb
<div class="container-fluid p-5 bg-light">
  <h2>Create Event</h2>

  <%= form_for @event do |f| %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
    </div>

    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_area :description, autofocus: true, autocomplete: "description" %>
    </div>

    <div class="field">
      <%= f.label :location %><br />
      <%= f.text_field :location, autofocus: true, autocomplete: "location" %>
    </div>

    <div class="field">
      <%= f.label :date %><br />
      <%= f.date_field :date, autofocus: true, autocomplete: "date" %>
    </div>

    <div class="field">
      <%= f.label :time %><br />
      <%= f.time_field :time, autofocus: true, autocomplete: "time" %>
    </div><br>

    <div class="actions">
      <%= f.submit "Create event" %>
    </div>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="jumbotron">
  <h1 class="display-2"><%= @event.name.capitalize %></h1><br>
  <hr class="my-1">
  <div class="shadow p-3 mb-5 bg-body-tertiary rounded">
    <p class="lead">Description: <%= @event.description %></p>
    <p class="lead">Location: <%= @event.location %></p>
    <p class="lead">Date: <%= @event.date.strftime('%d/%m/%y') %></p>
    <p class="lead">Time: <%= @event.time.strftime('%H:%m') %></p>
    <p class="lead">Created by: <%= link_to @event.creator.name, user_show_path(@event.creator) %></p>
    <% if @event.creator != current_user && !current_user.attended_events.include?(@event) %>
      <% if @event.date >= Time.now %>
        <%= button_to 'Attend event', attend_event_event_path(@event), method: :get %>
      <% end %>
    <% end %>
    <% if @event.creator == current_user %>
      <%= button_to 'Edit event', edit_event_path(@event), method: :get %>
    <% end %>
  </div>
</div>

<h5>Attendees:</h5><br>
<ol class="list-group list-group-numbered">
    <% @event.attendees.each do |attendee| %>
      <li class="list-group-item d-flex justify-content-between align-items-start">
        <div class="ms-2 me-auto">
          <div class="fw-bold"><%= link_to attendee.name, user_show_path(attendee) %></div>
        </div>
      </li>
    <% end %><br>
</ol>